import { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: 1,
    category: "sanduiche",
    name: "Misto",
    image: "/images/sanduiches/sanduiche-1.webp",
    price: 5,
  },
  {
    id: 2,
    category: "sanduiche",
    name: "X-Burger",
    image: "/images/sanduiches/sanduiche-2.webp",
    price: 7,
  },
  {
    id: 3,
    category: "sanduiche",
    name: "X-Salada",
    image: "/images/sanduiches/sanduiche-3.webp",
    price: 10,
  },
  {
    id: 4,
    category: "sanduiche",
    name: "X-Tudo",
    image: "/images/sanduiches/sanduiche-4.webp",
    price: 12,
  },
  {
    id: 11,
    category: "kikao",
    name: "Kikão Simples",
    image: "/images/kikoes/kikao-1.jpg",
    price: 3,
  },
  {
    id: 12,
    category: "kikao",
    name: "Kikão com Calabresa",
    image: "/images/kikoes/kikao-1.jpg",
    price: 5,
  },
  {
    id: 13,
    category: "kikao",
    name: "Kikão com frango",
    image: "/images/kikoes/kikao-1.jpg",
    price: 6,
  },
  {
    id: 21,
    category: "sushi",
    name: "Sushi 01",
    image: "/images/sushi/sushi1.png",
    price: 20,
  },
  {
    id: 22,
    category: "sushi",
    name: "Sushi 02",
    image: "/images/sushi/sushi2.png",
    price: 25,
  },
  {
    id: 23,
    category: "sushi",
    name: "Sushi 03",
    image: "/images/sushi/sushi3.png",
    price: 30,
  },
  {
    id: 24,
    category: "sushi",
    name: "Sushi 04",
    image: "/images/sushi/sushi4.png",
    price: 35,
  },
  {
    id: 25,
    category: "sushi",
    name: "Sushi 05",
    image: "/images/sushi/sushi5.png",
    price: 40,
  },
  {
    id: 26,
    category: "sushi",
    name: "Sushi 06",
    image: "/images/sushi/sushi6.png",
    price: 45,
  },
  {
    id: 27,
    category: "sushi",
    name: "Sushi 07",
    image: "/images/sushi/sushi7.png",
    price: 50,
  },
  {
    id: 28,
    category: "sushi",
    name: "Sushi 08",
    image: "/images/sushi/sushi8.png",
    price: 55,
  },
  {
    id: 29,
    category: "sushi",
    name: "Sushi 09",
    image: "/images/sushi/sushi9.png",
    price: 60,
  },
  {
    id: 31,
    category: "combo",
    name: "Combo 01",
    image: "/images/combo/combo1.png",
    price: 70,
  },
  {
    id: 32,
    category: "combo",
    name: "Combo 02",
    image: "/images/combo/combo2.png",
    price: 75,
  },
  {
    id: 33,
    category: "combo",
    name: "Combo 03",
    image: "/images/combo/combo3.png",
    price: 80,
  },
  {
    id: 34,
    category: "combo",
    name: "Combo 04",
    image: "/images/combo/combo4.png",
    price: 85,
  },
  {
    id: 35,
    category: "combo",
    name: "Combo 05",
    image: "/images/combo/combo5.png",
    price: 90,
  },
  {
    id: 36,
    category: "combo",
    name: "Combo 06",
    image: "/images/combo/combo6.png",
    price: 95,
  },
  {
    id: 37,
    category: "combo",
    name: "Combo 07",
    image: "/images/combo/combo7.png",
    price: 95,
  },
  {
    id: 38,
    category: "combo",
    name: "Combo 08",
    image: "/images/combo/combo8.png",
    price: 80,
  },
  {
    id: 39,
    category: "combo",
    name: "Combo 09",
    image: "/images/combo/combo9.png",
    price: 95,
  },
  {
    id: 42,
    category: "bebida",
    name: "Água",
    image: "/images/bebidas/Bebida2.png",
    price: 3,
  },
  {
    id: 43,
    category: "bebida",
    name: "Fanta Uva",
    image: "/images/bebidas/Bebida3.png",
    price: 5,
  },
  {
    id: 44,
    category: "bebida",
    name: "H2OH Limão",
    image: "/images/bebidas/Bebida4.png",
    price: 5,
  },
  {
    id: 45,
    category: "bebida",
    name: "Refrigrante de limão",
    image: "/images/bebidas/Bebida5.png",
    price: 5,
  },
  {
    id: 46,
    category: "bebida",
    name: "Coca Cola",
    image: "/images/bebidas/Bebida6.png",
    price: 6,
  },
  {
    id: 47,
    category: "bebida",
    name: "Suco de Manga",
    image: "/images/bebidas/Bebida7.png",
    price: 7,
  },
  {
    id: 48,
    category: "bebida",
    name: "Suco de Laranja",
    image: "/images/bebidas/Bebida8.png",
    price: 7,
  },
  {
    id: 49,
    category: "bebida",
    name: "Suco de Melância",
    image: "/images/bebidas/Bebida9.png",
    price: 6,
  },
];
